// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package config

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName           *string                     `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType         *string                     `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion         *string                     `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug               *bool                       `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce               *bool                       `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError             *string                     `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars            map[string]string           `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars       []string                    `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	ELMServer                 *string                     `mapstructure:"elm_server" validate:"required" cty:"elm_server" hcl:"elm_server"`
	ELMUsername               *string                     `mapstructure:"elm_username" validate:"required" cty:"elm_username" hcl:"elm_username"`
	ELMPassword               *string                     `mapstructure:"elm_password" validate:"required" cty:"elm_password" hcl:"elm_password"`
	InsecureConnection        *bool                       `mapstructure:"insecure_connection" cty:"insecure_connection" hcl:"insecure_connection"`
	WaitForIpTimeout          *int                        `mapstructure:"wait_for_ip_timeout" cty:"wait_for_ip_timeout" hcl:"wait_for_ip_timeout"`
	Type                      *string                     `mapstructure:"communicator" cty:"communicator" hcl:"communicator"`
	PauseBeforeConnect        *string                     `mapstructure:"pause_before_connecting" cty:"pause_before_connecting" hcl:"pause_before_connecting"`
	SSHHost                   *string                     `mapstructure:"ssh_host" cty:"ssh_host" hcl:"ssh_host"`
	SSHPort                   *int                        `mapstructure:"ssh_port" cty:"ssh_port" hcl:"ssh_port"`
	SSHUsername               *string                     `mapstructure:"ssh_username" cty:"ssh_username" hcl:"ssh_username"`
	SSHPassword               *string                     `mapstructure:"ssh_password" cty:"ssh_password" hcl:"ssh_password"`
	SSHKeyPairName            *string                     `mapstructure:"ssh_keypair_name" undocumented:"true" cty:"ssh_keypair_name" hcl:"ssh_keypair_name"`
	SSHTemporaryKeyPairName   *string                     `mapstructure:"temporary_key_pair_name" undocumented:"true" cty:"temporary_key_pair_name" hcl:"temporary_key_pair_name"`
	SSHTemporaryKeyPairType   *string                     `mapstructure:"temporary_key_pair_type" cty:"temporary_key_pair_type" hcl:"temporary_key_pair_type"`
	SSHTemporaryKeyPairBits   *int                        `mapstructure:"temporary_key_pair_bits" cty:"temporary_key_pair_bits" hcl:"temporary_key_pair_bits"`
	SSHCiphers                []string                    `mapstructure:"ssh_ciphers" cty:"ssh_ciphers" hcl:"ssh_ciphers"`
	SSHClearAuthorizedKeys    *bool                       `mapstructure:"ssh_clear_authorized_keys" cty:"ssh_clear_authorized_keys" hcl:"ssh_clear_authorized_keys"`
	SSHKEXAlgos               []string                    `mapstructure:"ssh_key_exchange_algorithms" cty:"ssh_key_exchange_algorithms" hcl:"ssh_key_exchange_algorithms"`
	SSHPrivateKeyFile         *string                     `mapstructure:"ssh_private_key_file" undocumented:"true" cty:"ssh_private_key_file" hcl:"ssh_private_key_file"`
	SSHCertificateFile        *string                     `mapstructure:"ssh_certificate_file" cty:"ssh_certificate_file" hcl:"ssh_certificate_file"`
	SSHPty                    *bool                       `mapstructure:"ssh_pty" cty:"ssh_pty" hcl:"ssh_pty"`
	SSHTimeout                *string                     `mapstructure:"ssh_timeout" cty:"ssh_timeout" hcl:"ssh_timeout"`
	SSHWaitTimeout            *string                     `mapstructure:"ssh_wait_timeout" undocumented:"true" cty:"ssh_wait_timeout" hcl:"ssh_wait_timeout"`
	SSHAgentAuth              *bool                       `mapstructure:"ssh_agent_auth" undocumented:"true" cty:"ssh_agent_auth" hcl:"ssh_agent_auth"`
	SSHDisableAgentForwarding *bool                       `mapstructure:"ssh_disable_agent_forwarding" cty:"ssh_disable_agent_forwarding" hcl:"ssh_disable_agent_forwarding"`
	SSHHandshakeAttempts      *int                        `mapstructure:"ssh_handshake_attempts" cty:"ssh_handshake_attempts" hcl:"ssh_handshake_attempts"`
	SSHBastionHost            *string                     `mapstructure:"ssh_bastion_host" cty:"ssh_bastion_host" hcl:"ssh_bastion_host"`
	SSHBastionPort            *int                        `mapstructure:"ssh_bastion_port" cty:"ssh_bastion_port" hcl:"ssh_bastion_port"`
	SSHBastionAgentAuth       *bool                       `mapstructure:"ssh_bastion_agent_auth" cty:"ssh_bastion_agent_auth" hcl:"ssh_bastion_agent_auth"`
	SSHBastionUsername        *string                     `mapstructure:"ssh_bastion_username" cty:"ssh_bastion_username" hcl:"ssh_bastion_username"`
	SSHBastionPassword        *string                     `mapstructure:"ssh_bastion_password" cty:"ssh_bastion_password" hcl:"ssh_bastion_password"`
	SSHBastionInteractive     *bool                       `mapstructure:"ssh_bastion_interactive" cty:"ssh_bastion_interactive" hcl:"ssh_bastion_interactive"`
	SSHBastionPrivateKeyFile  *string                     `mapstructure:"ssh_bastion_private_key_file" cty:"ssh_bastion_private_key_file" hcl:"ssh_bastion_private_key_file"`
	SSHBastionCertificateFile *string                     `mapstructure:"ssh_bastion_certificate_file" cty:"ssh_bastion_certificate_file" hcl:"ssh_bastion_certificate_file"`
	SSHFileTransferMethod     *string                     `mapstructure:"ssh_file_transfer_method" cty:"ssh_file_transfer_method" hcl:"ssh_file_transfer_method"`
	SSHProxyHost              *string                     `mapstructure:"ssh_proxy_host" cty:"ssh_proxy_host" hcl:"ssh_proxy_host"`
	SSHProxyPort              *int                        `mapstructure:"ssh_proxy_port" cty:"ssh_proxy_port" hcl:"ssh_proxy_port"`
	SSHProxyUsername          *string                     `mapstructure:"ssh_proxy_username" cty:"ssh_proxy_username" hcl:"ssh_proxy_username"`
	SSHProxyPassword          *string                     `mapstructure:"ssh_proxy_password" cty:"ssh_proxy_password" hcl:"ssh_proxy_password"`
	SSHKeepAliveInterval      *string                     `mapstructure:"ssh_keep_alive_interval" cty:"ssh_keep_alive_interval" hcl:"ssh_keep_alive_interval"`
	SSHReadWriteTimeout       *string                     `mapstructure:"ssh_read_write_timeout" cty:"ssh_read_write_timeout" hcl:"ssh_read_write_timeout"`
	SSHRemoteTunnels          []string                    `mapstructure:"ssh_remote_tunnels" cty:"ssh_remote_tunnels" hcl:"ssh_remote_tunnels"`
	SSHLocalTunnels           []string                    `mapstructure:"ssh_local_tunnels" cty:"ssh_local_tunnels" hcl:"ssh_local_tunnels"`
	SSHPublicKey              []byte                      `mapstructure:"ssh_public_key" undocumented:"true" cty:"ssh_public_key" hcl:"ssh_public_key"`
	SSHPrivateKey             []byte                      `mapstructure:"ssh_private_key" undocumented:"true" cty:"ssh_private_key" hcl:"ssh_private_key"`
	WinRMUser                 *string                     `mapstructure:"winrm_username" cty:"winrm_username" hcl:"winrm_username"`
	WinRMPassword             *string                     `mapstructure:"winrm_password" cty:"winrm_password" hcl:"winrm_password"`
	WinRMHost                 *string                     `mapstructure:"winrm_host" cty:"winrm_host" hcl:"winrm_host"`
	WinRMNoProxy              *bool                       `mapstructure:"winrm_no_proxy" cty:"winrm_no_proxy" hcl:"winrm_no_proxy"`
	WinRMPort                 *int                        `mapstructure:"winrm_port" cty:"winrm_port" hcl:"winrm_port"`
	WinRMTimeout              *string                     `mapstructure:"winrm_timeout" cty:"winrm_timeout" hcl:"winrm_timeout"`
	WinRMUseSSL               *bool                       `mapstructure:"winrm_use_ssl" cty:"winrm_use_ssl" hcl:"winrm_use_ssl"`
	WinRMInsecure             *bool                       `mapstructure:"winrm_insecure" cty:"winrm_insecure" hcl:"winrm_insecure"`
	WinRMUseNTLM              *bool                       `mapstructure:"winrm_use_ntlm" cty:"winrm_use_ntlm" hcl:"winrm_use_ntlm"`
	CreateApp                 *FlatCreateAppConfig        `mapstructure:"create_app_layer" validate:"required_without_all=CreatePlatform RevisionOs RevisionPlatform RevisionApp ConnectOnly" cty:"create_app_layer" hcl:"create_app_layer"`
	CreatePlatform            *FlatCreatePlatformConfig   `mapstructure:"create_platform_layer" validate:"required_without_all=CreateApp RevisionOs RevisionPlatform RevisionApp ConnectOnly" cty:"create_platform_layer" hcl:"create_platform_layer"`
	RevisionOs                *FlatRevisionOsConfig       `mapstructure:"revision_os_layer" validate:"required_without_all=CreateApp CreatePlatform RevisionPlatform RevisionApp ConnectOnly" cty:"revision_os_layer" hcl:"revision_os_layer"`
	RevisionPlatform          *FlatRevisionPlatformConfig `mapstructure:"revision_platform_layer" validate:"required_without_all=CreateApp CreatePlatform RevisionOs RevisionApp ConnectOnly" cty:"revision_platform_layer" hcl:"revision_platform_layer"`
	RevisionApp               *FlatRevisionAppConfig      `mapstructure:"revision_app_layer" validate:"required_without_all=CreateApp CreatePlatform RevisionOs RevisionPlatform ConnectOnly" cty:"revision_app_layer" hcl:"revision_app_layer"`
	ConnectOnly               *FlatConnectOnlyConfig      `mapstructure:"connect_only" validate:"required_without_all=CreateApp CreatePlatform RevisionOs RevisionPlatform RevisionApp" cty:"connect_only" hcl:"connect_only"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":            &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":          &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":          &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":                 &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":                 &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":              &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":        &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables":   &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"elm_server":                   &hcldec.AttrSpec{Name: "elm_server", Type: cty.String, Required: false},
		"elm_username":                 &hcldec.AttrSpec{Name: "elm_username", Type: cty.String, Required: false},
		"elm_password":                 &hcldec.AttrSpec{Name: "elm_password", Type: cty.String, Required: false},
		"insecure_connection":          &hcldec.AttrSpec{Name: "insecure_connection", Type: cty.Bool, Required: false},
		"wait_for_ip_timeout":          &hcldec.AttrSpec{Name: "wait_for_ip_timeout", Type: cty.Number, Required: false},
		"communicator":                 &hcldec.AttrSpec{Name: "communicator", Type: cty.String, Required: false},
		"pause_before_connecting":      &hcldec.AttrSpec{Name: "pause_before_connecting", Type: cty.String, Required: false},
		"ssh_host":                     &hcldec.AttrSpec{Name: "ssh_host", Type: cty.String, Required: false},
		"ssh_port":                     &hcldec.AttrSpec{Name: "ssh_port", Type: cty.Number, Required: false},
		"ssh_username":                 &hcldec.AttrSpec{Name: "ssh_username", Type: cty.String, Required: false},
		"ssh_password":                 &hcldec.AttrSpec{Name: "ssh_password", Type: cty.String, Required: false},
		"ssh_keypair_name":             &hcldec.AttrSpec{Name: "ssh_keypair_name", Type: cty.String, Required: false},
		"temporary_key_pair_name":      &hcldec.AttrSpec{Name: "temporary_key_pair_name", Type: cty.String, Required: false},
		"temporary_key_pair_type":      &hcldec.AttrSpec{Name: "temporary_key_pair_type", Type: cty.String, Required: false},
		"temporary_key_pair_bits":      &hcldec.AttrSpec{Name: "temporary_key_pair_bits", Type: cty.Number, Required: false},
		"ssh_ciphers":                  &hcldec.AttrSpec{Name: "ssh_ciphers", Type: cty.List(cty.String), Required: false},
		"ssh_clear_authorized_keys":    &hcldec.AttrSpec{Name: "ssh_clear_authorized_keys", Type: cty.Bool, Required: false},
		"ssh_key_exchange_algorithms":  &hcldec.AttrSpec{Name: "ssh_key_exchange_algorithms", Type: cty.List(cty.String), Required: false},
		"ssh_private_key_file":         &hcldec.AttrSpec{Name: "ssh_private_key_file", Type: cty.String, Required: false},
		"ssh_certificate_file":         &hcldec.AttrSpec{Name: "ssh_certificate_file", Type: cty.String, Required: false},
		"ssh_pty":                      &hcldec.AttrSpec{Name: "ssh_pty", Type: cty.Bool, Required: false},
		"ssh_timeout":                  &hcldec.AttrSpec{Name: "ssh_timeout", Type: cty.String, Required: false},
		"ssh_wait_timeout":             &hcldec.AttrSpec{Name: "ssh_wait_timeout", Type: cty.String, Required: false},
		"ssh_agent_auth":               &hcldec.AttrSpec{Name: "ssh_agent_auth", Type: cty.Bool, Required: false},
		"ssh_disable_agent_forwarding": &hcldec.AttrSpec{Name: "ssh_disable_agent_forwarding", Type: cty.Bool, Required: false},
		"ssh_handshake_attempts":       &hcldec.AttrSpec{Name: "ssh_handshake_attempts", Type: cty.Number, Required: false},
		"ssh_bastion_host":             &hcldec.AttrSpec{Name: "ssh_bastion_host", Type: cty.String, Required: false},
		"ssh_bastion_port":             &hcldec.AttrSpec{Name: "ssh_bastion_port", Type: cty.Number, Required: false},
		"ssh_bastion_agent_auth":       &hcldec.AttrSpec{Name: "ssh_bastion_agent_auth", Type: cty.Bool, Required: false},
		"ssh_bastion_username":         &hcldec.AttrSpec{Name: "ssh_bastion_username", Type: cty.String, Required: false},
		"ssh_bastion_password":         &hcldec.AttrSpec{Name: "ssh_bastion_password", Type: cty.String, Required: false},
		"ssh_bastion_interactive":      &hcldec.AttrSpec{Name: "ssh_bastion_interactive", Type: cty.Bool, Required: false},
		"ssh_bastion_private_key_file": &hcldec.AttrSpec{Name: "ssh_bastion_private_key_file", Type: cty.String, Required: false},
		"ssh_bastion_certificate_file": &hcldec.AttrSpec{Name: "ssh_bastion_certificate_file", Type: cty.String, Required: false},
		"ssh_file_transfer_method":     &hcldec.AttrSpec{Name: "ssh_file_transfer_method", Type: cty.String, Required: false},
		"ssh_proxy_host":               &hcldec.AttrSpec{Name: "ssh_proxy_host", Type: cty.String, Required: false},
		"ssh_proxy_port":               &hcldec.AttrSpec{Name: "ssh_proxy_port", Type: cty.Number, Required: false},
		"ssh_proxy_username":           &hcldec.AttrSpec{Name: "ssh_proxy_username", Type: cty.String, Required: false},
		"ssh_proxy_password":           &hcldec.AttrSpec{Name: "ssh_proxy_password", Type: cty.String, Required: false},
		"ssh_keep_alive_interval":      &hcldec.AttrSpec{Name: "ssh_keep_alive_interval", Type: cty.String, Required: false},
		"ssh_read_write_timeout":       &hcldec.AttrSpec{Name: "ssh_read_write_timeout", Type: cty.String, Required: false},
		"ssh_remote_tunnels":           &hcldec.AttrSpec{Name: "ssh_remote_tunnels", Type: cty.List(cty.String), Required: false},
		"ssh_local_tunnels":            &hcldec.AttrSpec{Name: "ssh_local_tunnels", Type: cty.List(cty.String), Required: false},
		"ssh_public_key":               &hcldec.AttrSpec{Name: "ssh_public_key", Type: cty.List(cty.Number), Required: false},
		"ssh_private_key":              &hcldec.AttrSpec{Name: "ssh_private_key", Type: cty.List(cty.Number), Required: false},
		"winrm_username":               &hcldec.AttrSpec{Name: "winrm_username", Type: cty.String, Required: false},
		"winrm_password":               &hcldec.AttrSpec{Name: "winrm_password", Type: cty.String, Required: false},
		"winrm_host":                   &hcldec.AttrSpec{Name: "winrm_host", Type: cty.String, Required: false},
		"winrm_no_proxy":               &hcldec.AttrSpec{Name: "winrm_no_proxy", Type: cty.Bool, Required: false},
		"winrm_port":                   &hcldec.AttrSpec{Name: "winrm_port", Type: cty.Number, Required: false},
		"winrm_timeout":                &hcldec.AttrSpec{Name: "winrm_timeout", Type: cty.String, Required: false},
		"winrm_use_ssl":                &hcldec.AttrSpec{Name: "winrm_use_ssl", Type: cty.Bool, Required: false},
		"winrm_insecure":               &hcldec.AttrSpec{Name: "winrm_insecure", Type: cty.Bool, Required: false},
		"winrm_use_ntlm":               &hcldec.AttrSpec{Name: "winrm_use_ntlm", Type: cty.Bool, Required: false},
		"create_app_layer":             &hcldec.BlockSpec{TypeName: "create_app_layer", Nested: hcldec.ObjectSpec((*FlatCreateAppConfig)(nil).HCL2Spec())},
		"create_platform_layer":        &hcldec.BlockSpec{TypeName: "create_platform_layer", Nested: hcldec.ObjectSpec((*FlatCreatePlatformConfig)(nil).HCL2Spec())},
		"revision_os_layer":            &hcldec.BlockSpec{TypeName: "revision_os_layer", Nested: hcldec.ObjectSpec((*FlatRevisionOsConfig)(nil).HCL2Spec())},
		"revision_platform_layer":      &hcldec.BlockSpec{TypeName: "revision_platform_layer", Nested: hcldec.ObjectSpec((*FlatRevisionPlatformConfig)(nil).HCL2Spec())},
		"revision_app_layer":           &hcldec.BlockSpec{TypeName: "revision_app_layer", Nested: hcldec.ObjectSpec((*FlatRevisionAppConfig)(nil).HCL2Spec())},
		"connect_only":                 &hcldec.BlockSpec{TypeName: "connect_only", Nested: hcldec.ObjectSpec((*FlatConnectOnlyConfig)(nil).HCL2Spec())},
	}
	return s
}

// FlatConnectOnlyConfig is an auto-generated flat version of ConnectOnlyConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConnectOnlyConfig struct {
	OperationType *string `mapstructure:"operation_type" validate:"required" cty:"operation_type" hcl:"operation_type"`
	LayerName     *string `mapstructure:"layer_name" validate:"required" cty:"layer_name" hcl:"layer_name"`
}

// FlatMapstructure returns a new FlatConnectOnlyConfig.
// FlatConnectOnlyConfig is an auto-generated flat version of ConnectOnlyConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*ConnectOnlyConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConnectOnlyConfig)
}

// HCL2Spec returns the hcl spec of a ConnectOnlyConfig.
// This spec is used by HCL to read the fields of ConnectOnlyConfig.
// The decoded values from this spec will then be applied to a FlatConnectOnlyConfig.
func (*FlatConnectOnlyConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"operation_type": &hcldec.AttrSpec{Name: "operation_type", Type: cty.String, Required: false},
		"layer_name":     &hcldec.AttrSpec{Name: "layer_name", Type: cty.String, Required: false},
	}
	return s
}

// FlatCreateAppConfig is an auto-generated flat version of CreateAppConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatCreateAppConfig struct {
	OsLayerName                 *string  `mapstructure:"os_layer_name" validate:"required" cty:"os_layer_name" hcl:"os_layer_name"`
	OsLayerVersionName          *string  `mapstructure:"os_layer_version_name" validate:"required" cty:"os_layer_version_name" hcl:"os_layer_version_name"`
	PlatformLayerName           *string  `mapstructure:"platform_layer_name" cty:"platform_layer_name" hcl:"platform_layer_name"`
	PlatformLayerVersionName    *string  `mapstructure:"platform_layer_version_name" cty:"platform_layer_version_name" hcl:"platform_layer_version_name"`
	PrerequisiteLayers          []string `mapstructure:"prerequisite_layers" cty:"prerequisite_layers" hcl:"prerequisite_layers"`
	LayerName                   *string  `mapstructure:"layer_name" validate:"required" cty:"layer_name" hcl:"layer_name"`
	PackagingDiskFileName       *string  `mapstructure:"packaging_disk_file_name" cty:"packaging_disk_file_name" hcl:"packaging_disk_file_name"`
	PlatformConnectorConfigName *string  `mapstructure:"platform_connector_config_name" validate:"required" cty:"platform_connector_config_name" hcl:"platform_connector_config_name"`
	IconId                      *int64   `mapstructure:"icon_id" cty:"icon_id" hcl:"icon_id"`
	VersionName                 *string  `mapstructure:"version_name" validate:"required" cty:"version_name" hcl:"version_name"`
	VersionDescription          *string  `mapstructure:"version_description" cty:"version_description" hcl:"version_description"`
	VersionSizeGb               *int32   `mapstructure:"version_size_gb" cty:"version_size_gb" hcl:"version_size_gb"`
	Comment                     *string  `mapstructure:"comment" cty:"comment" hcl:"comment"`
	SkipCleanupOnFailure        *bool    `mapstructure:"skip_cleanup_on_failure" cty:"skip_cleanup_on_failure" hcl:"skip_cleanup_on_failure"`
}

// FlatMapstructure returns a new FlatCreateAppConfig.
// FlatCreateAppConfig is an auto-generated flat version of CreateAppConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*CreateAppConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatCreateAppConfig)
}

// HCL2Spec returns the hcl spec of a CreateAppConfig.
// This spec is used by HCL to read the fields of CreateAppConfig.
// The decoded values from this spec will then be applied to a FlatCreateAppConfig.
func (*FlatCreateAppConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"os_layer_name":                  &hcldec.AttrSpec{Name: "os_layer_name", Type: cty.String, Required: false},
		"os_layer_version_name":          &hcldec.AttrSpec{Name: "os_layer_version_name", Type: cty.String, Required: false},
		"platform_layer_name":            &hcldec.AttrSpec{Name: "platform_layer_name", Type: cty.String, Required: false},
		"platform_layer_version_name":    &hcldec.AttrSpec{Name: "platform_layer_version_name", Type: cty.String, Required: false},
		"prerequisite_layers":            &hcldec.AttrSpec{Name: "prerequisite_layers", Type: cty.List(cty.String), Required: false},
		"layer_name":                     &hcldec.AttrSpec{Name: "layer_name", Type: cty.String, Required: false},
		"packaging_disk_file_name":       &hcldec.AttrSpec{Name: "packaging_disk_file_name", Type: cty.String, Required: false},
		"platform_connector_config_name": &hcldec.AttrSpec{Name: "platform_connector_config_name", Type: cty.String, Required: false},
		"icon_id":                        &hcldec.AttrSpec{Name: "icon_id", Type: cty.Number, Required: false},
		"version_name":                   &hcldec.AttrSpec{Name: "version_name", Type: cty.String, Required: false},
		"version_description":            &hcldec.AttrSpec{Name: "version_description", Type: cty.String, Required: false},
		"version_size_gb":                &hcldec.AttrSpec{Name: "version_size_gb", Type: cty.Number, Required: false},
		"comment":                        &hcldec.AttrSpec{Name: "comment", Type: cty.String, Required: false},
		"skip_cleanup_on_failure":        &hcldec.AttrSpec{Name: "skip_cleanup_on_failure", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatCreatePlatformConfig is an auto-generated flat version of CreatePlatformConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatCreatePlatformConfig struct {
	HypervisorPlatform          *string `mapstructure:"hypervisor_platform" validate:"required" cty:"hypervisor_platform" hcl:"hypervisor_platform"`
	ProvisioningPlatform        *string `mapstructure:"provisioning_platform" validate:"required" cty:"provisioning_platform" hcl:"provisioning_platform"`
	BrokerPlatform              *string `mapstructure:"broker_platform" validate:"required" cty:"broker_platform" hcl:"broker_platform"`
	OsLayerName                 *string `mapstructure:"os_layer_name" validate:"required" cty:"os_layer_name" hcl:"os_layer_name"`
	OsLayerVersionName          *string `mapstructure:"os_layer_version_name" validate:"required" cty:"os_layer_version_name" hcl:"os_layer_version_name"`
	LayerName                   *string `mapstructure:"layer_name" validate:"required" cty:"layer_name" hcl:"layer_name"`
	PackagingDiskFileName       *string `mapstructure:"packaging_disk_file_name" cty:"packaging_disk_file_name" hcl:"packaging_disk_file_name"`
	PlatformConnectorConfigName *string `mapstructure:"platform_connector_config_name" validate:"required" cty:"platform_connector_config_name" hcl:"platform_connector_config_name"`
	IconId                      *int64  `mapstructure:"icon_id" cty:"icon_id" hcl:"icon_id"`
	VersionName                 *string `mapstructure:"version_name" validate:"required" cty:"version_name" hcl:"version_name"`
	VersionDescription          *string `mapstructure:"version_description" cty:"version_description" hcl:"version_description"`
	VersionSizeGb               *int32  `mapstructure:"version_size_gb" cty:"version_size_gb" hcl:"version_size_gb"`
	Comment                     *string `mapstructure:"comment" cty:"comment" hcl:"comment"`
	SkipCleanupOnFailure        *bool   `mapstructure:"skip_cleanup_on_failure" cty:"skip_cleanup_on_failure" hcl:"skip_cleanup_on_failure"`
}

// FlatMapstructure returns a new FlatCreatePlatformConfig.
// FlatCreatePlatformConfig is an auto-generated flat version of CreatePlatformConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*CreatePlatformConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatCreatePlatformConfig)
}

// HCL2Spec returns the hcl spec of a CreatePlatformConfig.
// This spec is used by HCL to read the fields of CreatePlatformConfig.
// The decoded values from this spec will then be applied to a FlatCreatePlatformConfig.
func (*FlatCreatePlatformConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"hypervisor_platform":            &hcldec.AttrSpec{Name: "hypervisor_platform", Type: cty.String, Required: false},
		"provisioning_platform":          &hcldec.AttrSpec{Name: "provisioning_platform", Type: cty.String, Required: false},
		"broker_platform":                &hcldec.AttrSpec{Name: "broker_platform", Type: cty.String, Required: false},
		"os_layer_name":                  &hcldec.AttrSpec{Name: "os_layer_name", Type: cty.String, Required: false},
		"os_layer_version_name":          &hcldec.AttrSpec{Name: "os_layer_version_name", Type: cty.String, Required: false},
		"layer_name":                     &hcldec.AttrSpec{Name: "layer_name", Type: cty.String, Required: false},
		"packaging_disk_file_name":       &hcldec.AttrSpec{Name: "packaging_disk_file_name", Type: cty.String, Required: false},
		"platform_connector_config_name": &hcldec.AttrSpec{Name: "platform_connector_config_name", Type: cty.String, Required: false},
		"icon_id":                        &hcldec.AttrSpec{Name: "icon_id", Type: cty.Number, Required: false},
		"version_name":                   &hcldec.AttrSpec{Name: "version_name", Type: cty.String, Required: false},
		"version_description":            &hcldec.AttrSpec{Name: "version_description", Type: cty.String, Required: false},
		"version_size_gb":                &hcldec.AttrSpec{Name: "version_size_gb", Type: cty.Number, Required: false},
		"comment":                        &hcldec.AttrSpec{Name: "comment", Type: cty.String, Required: false},
		"skip_cleanup_on_failure":        &hcldec.AttrSpec{Name: "skip_cleanup_on_failure", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatRevisionAppConfig is an auto-generated flat version of RevisionAppConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatRevisionAppConfig struct {
	OsLayerName                 *string  `mapstructure:"os_layer_name" validate:"required" cty:"os_layer_name" hcl:"os_layer_name"`
	OsLayerVersionName          *string  `mapstructure:"os_layer_version_name" validate:"required" cty:"os_layer_version_name" hcl:"os_layer_version_name"`
	PlatformLayerName           *string  `mapstructure:"platform_layer_name" cty:"platform_layer_name" hcl:"platform_layer_name"`
	PlatformLayerVersionName    *string  `mapstructure:"platform_layer_version_name" cty:"platform_layer_version_name" hcl:"platform_layer_version_name"`
	LayerName                   *string  `mapstructure:"layer_name" validate:"required" cty:"layer_name" hcl:"layer_name"`
	BaseVersionName             *string  `mapstructure:"base_version_name" cty:"base_version_name" hcl:"base_version_name"`
	PrerequisiteLayers          []string `mapstructure:"prerequisite_layers" cty:"prerequisite_layers" hcl:"prerequisite_layers"`
	PackagingDiskFileName       *string  `mapstructure:"packaging_disk_file_name" cty:"packaging_disk_file_name" hcl:"packaging_disk_file_name"`
	PlatformConnectorConfigName *string  `mapstructure:"platform_connector_config_name" validate:"required" cty:"platform_connector_config_name" hcl:"platform_connector_config_name"`
	VersionName                 *string  `mapstructure:"version_name" validate:"required" cty:"version_name" hcl:"version_name"`
	VersionDescription          *string  `mapstructure:"version_description" cty:"version_description" hcl:"version_description"`
	VersionSizeGb               *int32   `mapstructure:"version_size_gb" cty:"version_size_gb" hcl:"version_size_gb"`
	Comment                     *string  `mapstructure:"comment" cty:"comment" hcl:"comment"`
	SkipCleanupOnFailure        *bool    `mapstructure:"skip_cleanup_on_failure" cty:"skip_cleanup_on_failure" hcl:"skip_cleanup_on_failure"`
}

// FlatMapstructure returns a new FlatRevisionAppConfig.
// FlatRevisionAppConfig is an auto-generated flat version of RevisionAppConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*RevisionAppConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatRevisionAppConfig)
}

// HCL2Spec returns the hcl spec of a RevisionAppConfig.
// This spec is used by HCL to read the fields of RevisionAppConfig.
// The decoded values from this spec will then be applied to a FlatRevisionAppConfig.
func (*FlatRevisionAppConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"os_layer_name":                  &hcldec.AttrSpec{Name: "os_layer_name", Type: cty.String, Required: false},
		"os_layer_version_name":          &hcldec.AttrSpec{Name: "os_layer_version_name", Type: cty.String, Required: false},
		"platform_layer_name":            &hcldec.AttrSpec{Name: "platform_layer_name", Type: cty.String, Required: false},
		"platform_layer_version_name":    &hcldec.AttrSpec{Name: "platform_layer_version_name", Type: cty.String, Required: false},
		"layer_name":                     &hcldec.AttrSpec{Name: "layer_name", Type: cty.String, Required: false},
		"base_version_name":              &hcldec.AttrSpec{Name: "base_version_name", Type: cty.String, Required: false},
		"prerequisite_layers":            &hcldec.AttrSpec{Name: "prerequisite_layers", Type: cty.List(cty.String), Required: false},
		"packaging_disk_file_name":       &hcldec.AttrSpec{Name: "packaging_disk_file_name", Type: cty.String, Required: false},
		"platform_connector_config_name": &hcldec.AttrSpec{Name: "platform_connector_config_name", Type: cty.String, Required: false},
		"version_name":                   &hcldec.AttrSpec{Name: "version_name", Type: cty.String, Required: false},
		"version_description":            &hcldec.AttrSpec{Name: "version_description", Type: cty.String, Required: false},
		"version_size_gb":                &hcldec.AttrSpec{Name: "version_size_gb", Type: cty.Number, Required: false},
		"comment":                        &hcldec.AttrSpec{Name: "comment", Type: cty.String, Required: false},
		"skip_cleanup_on_failure":        &hcldec.AttrSpec{Name: "skip_cleanup_on_failure", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatRevisionOsConfig is an auto-generated flat version of RevisionOsConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatRevisionOsConfig struct {
	LayerName                   *string `mapstructure:"layer_name" validate:"required" cty:"layer_name" hcl:"layer_name"`
	BaseVersionName             *string `mapstructure:"base_version_name" validate:"required" cty:"base_version_name" hcl:"base_version_name"`
	PackagingDiskFileName       *string `mapstructure:"packaging_disk_file_name" cty:"packaging_disk_file_name" hcl:"packaging_disk_file_name"`
	PlatformConnectorConfigName *string `mapstructure:"platform_connector_config_name" validate:"required" cty:"platform_connector_config_name" hcl:"platform_connector_config_name"`
	VersionName                 *string `mapstructure:"version_name" validate:"required" cty:"version_name" hcl:"version_name"`
	VersionDescription          *string `mapstructure:"version_description" cty:"version_description" hcl:"version_description"`
	VersionSizeGb               *int32  `mapstructure:"version_size_gb" cty:"version_size_gb" hcl:"version_size_gb"`
	Comment                     *string `mapstructure:"comment" cty:"comment" hcl:"comment"`
	SkipCleanupOnFailure        *bool   `mapstructure:"skip_cleanup_on_failure" cty:"skip_cleanup_on_failure" hcl:"skip_cleanup_on_failure"`
}

// FlatMapstructure returns a new FlatRevisionOsConfig.
// FlatRevisionOsConfig is an auto-generated flat version of RevisionOsConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*RevisionOsConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatRevisionOsConfig)
}

// HCL2Spec returns the hcl spec of a RevisionOsConfig.
// This spec is used by HCL to read the fields of RevisionOsConfig.
// The decoded values from this spec will then be applied to a FlatRevisionOsConfig.
func (*FlatRevisionOsConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"layer_name":                     &hcldec.AttrSpec{Name: "layer_name", Type: cty.String, Required: false},
		"base_version_name":              &hcldec.AttrSpec{Name: "base_version_name", Type: cty.String, Required: false},
		"packaging_disk_file_name":       &hcldec.AttrSpec{Name: "packaging_disk_file_name", Type: cty.String, Required: false},
		"platform_connector_config_name": &hcldec.AttrSpec{Name: "platform_connector_config_name", Type: cty.String, Required: false},
		"version_name":                   &hcldec.AttrSpec{Name: "version_name", Type: cty.String, Required: false},
		"version_description":            &hcldec.AttrSpec{Name: "version_description", Type: cty.String, Required: false},
		"version_size_gb":                &hcldec.AttrSpec{Name: "version_size_gb", Type: cty.Number, Required: false},
		"comment":                        &hcldec.AttrSpec{Name: "comment", Type: cty.String, Required: false},
		"skip_cleanup_on_failure":        &hcldec.AttrSpec{Name: "skip_cleanup_on_failure", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatRevisionPlatformConfig is an auto-generated flat version of RevisionPlatformConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatRevisionPlatformConfig struct {
	HypervisorPlatform          *string `mapstructure:"hypervisor_platform" cty:"hypervisor_platform" hcl:"hypervisor_platform"`
	ProvisioningPlatform        *string `mapstructure:"provisioning_platform" cty:"provisioning_platform" hcl:"provisioning_platform"`
	BrokerPlatform              *string `mapstructure:"broker_platform" cty:"broker_platform" hcl:"broker_platform"`
	OsLayerName                 *string `mapstructure:"os_layer_name" validate:"required" cty:"os_layer_name" hcl:"os_layer_name"`
	OsLayerVersionName          *string `mapstructure:"os_layer_version_name" validate:"required" cty:"os_layer_version_name" hcl:"os_layer_version_name"`
	LayerName                   *string `mapstructure:"layer_name" validate:"required" cty:"layer_name" hcl:"layer_name"`
	BaseVersionName             *string `mapstructure:"base_version_name" validate:"required" cty:"base_version_name" hcl:"base_version_name"`
	PackagingDiskFileName       *string `mapstructure:"packaging_disk_file_name" cty:"packaging_disk_file_name" hcl:"packaging_disk_file_name"`
	PlatformConnectorConfigName *string `mapstructure:"platform_connector_config_name" validate:"required" cty:"platform_connector_config_name" hcl:"platform_connector_config_name"`
	VersionName                 *string `mapstructure:"version_name" validate:"required" cty:"version_name" hcl:"version_name"`
	VersionDescription          *string `mapstructure:"version_description" cty:"version_description" hcl:"version_description"`
	VersionSizeGb               *int32  `mapstructure:"version_size_gb" cty:"version_size_gb" hcl:"version_size_gb"`
	Comment                     *string `mapstructure:"comment" cty:"comment" hcl:"comment"`
	SkipCleanupOnFailure        *bool   `mapstructure:"skip_cleanup_on_failure" cty:"skip_cleanup_on_failure" hcl:"skip_cleanup_on_failure"`
}

// FlatMapstructure returns a new FlatRevisionPlatformConfig.
// FlatRevisionPlatformConfig is an auto-generated flat version of RevisionPlatformConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*RevisionPlatformConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatRevisionPlatformConfig)
}

// HCL2Spec returns the hcl spec of a RevisionPlatformConfig.
// This spec is used by HCL to read the fields of RevisionPlatformConfig.
// The decoded values from this spec will then be applied to a FlatRevisionPlatformConfig.
func (*FlatRevisionPlatformConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"hypervisor_platform":            &hcldec.AttrSpec{Name: "hypervisor_platform", Type: cty.String, Required: false},
		"provisioning_platform":          &hcldec.AttrSpec{Name: "provisioning_platform", Type: cty.String, Required: false},
		"broker_platform":                &hcldec.AttrSpec{Name: "broker_platform", Type: cty.String, Required: false},
		"os_layer_name":                  &hcldec.AttrSpec{Name: "os_layer_name", Type: cty.String, Required: false},
		"os_layer_version_name":          &hcldec.AttrSpec{Name: "os_layer_version_name", Type: cty.String, Required: false},
		"layer_name":                     &hcldec.AttrSpec{Name: "layer_name", Type: cty.String, Required: false},
		"base_version_name":              &hcldec.AttrSpec{Name: "base_version_name", Type: cty.String, Required: false},
		"packaging_disk_file_name":       &hcldec.AttrSpec{Name: "packaging_disk_file_name", Type: cty.String, Required: false},
		"platform_connector_config_name": &hcldec.AttrSpec{Name: "platform_connector_config_name", Type: cty.String, Required: false},
		"version_name":                   &hcldec.AttrSpec{Name: "version_name", Type: cty.String, Required: false},
		"version_description":            &hcldec.AttrSpec{Name: "version_description", Type: cty.String, Required: false},
		"version_size_gb":                &hcldec.AttrSpec{Name: "version_size_gb", Type: cty.Number, Required: false},
		"comment":                        &hcldec.AttrSpec{Name: "comment", Type: cty.String, Required: false},
		"skip_cleanup_on_failure":        &hcldec.AttrSpec{Name: "skip_cleanup_on_failure", Type: cty.Bool, Required: false},
	}
	return s
}
